const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const DISPLAY_NOTIFICATION_DRAWER = 'DISPLAY_NOTIFICATION_DRAWER';
const HIDE_NOTIFICATION_DRAWER = 'HIDE_NOTIFICATION_DRAWER';

module.exports = {
    LOGIN,
    LOGOUT,
    DISPLAY_NOTIFICATION_DRAWER,
    HIDE_NOTIFICATION_DRAWER,
};
